-- GENERATED by `bun run db:generate` (console/db/generate.ts).
--
-- Produced by better-auth's own migration compiler
-- (`better-auth/db/migration` → `getMigrations().compileMigrations()`) at the
-- version pinned in package.json. `--fresh` diffs against an empty database and
-- emits the whole schema; without it, against a database that already has the
-- earlier migrations, and emits only what is new.
--
-- DO NOT EDIT. `db/migrate.ts` records a SHA-256 of this file when it is
-- applied and refuses to run once the content has changed. A better-auth
-- upgrade that alters the schema produces the NEXT numbered file; regenerating
-- this one in place would leave migrated and unmigrated environments disagreeing
-- with nothing to show for it.
--
-- Verified by `tests/integration/console-db-migrations.test.ts`: after every
-- committed migration is applied, better-auth must report nothing left to
-- create or add.

create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "jwks" ("id" text not null primary key, "publicKey" text not null, "privateKey" text not null, "createdAt" timestamptz not null, "expiresAt" timestamptz);

create table "rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");
