// Emit the DDL Better Auth wants but the database does not yet have.
//
// This is `@better-auth/cli generate`, at the version this console actually
// runs — see the version note at the top of `db/schema.ts` for why the CLI
// itself cannot be used.
//
// USAGE
//
//   bun run db:generate                 # diff against $CONSOLE_DATABASE_URL
//   bun run db:generate -- --fresh      # full schema, via a temporary database
//
// The output goes to stdout so it can be redirected into the next numbered file:
//
//   bun run db:generate -- --fresh > db/migrations/0001_better_auth_core.sql
//
// NEVER edit a migration that has already been applied anywhere — `db/migrate.ts`
// records a checksum per file and refuses. A better-auth upgrade that changes
// the schema produces the NEXT number, not a rewrite of the first.
//
// The gate that notices such an upgrade is not this script: it is
// `tests/integration/console-db-migrations.test.ts`, which applies every
// committed migration to a real database and then asserts Better Auth reports
// nothing left to create or add.
import { randomBytes } from "node:crypto";

import { getMigrations } from "better-auth/db/migration";
import { Pool } from "pg";

import { redactDsn, resolveDsn, scriptPool, splitDatabase } from "./dsn";
import { consoleAuthSchemaOptions } from "./schema";

/**
 * Run `body` against a brand-new empty database, then drop it.
 *
 * "What is the full schema?" is only answerable against an empty database:
 * `getMigrations` reports a DIFF, so run against a migrated database it
 * correctly reports nothing.
 */
export async function withTemporaryDatabase<T>(
  dsn: string,
  body: (temporaryDsn: string) => Promise<T>,
): Promise<T> {
  const { admin } = splitDatabase(dsn);
  const name = `console_auth_gen_${randomBytes(8).toString("hex")}`;
  const adminPool = new Pool({ connectionString: admin, max: 1 });
  try {
    await adminPool.query(`create database "${name}"`);
  } catch (error) {
    await adminPool.end();
    throw new Error(
      `could not create the temporary database ${name} on ${redactDsn(admin)}: ` +
        `${(error as Error).message}`,
    );
  }

  const temporary = new URL(dsn);
  temporary.pathname = `/${name}`;
  try {
    return await body(temporary.toString());
  } finally {
    // `force` terminates any connection the pool did not close in time;
    // without it a dropped-then-recreated temporary name accumulates.
    await adminPool.query(`drop database if exists "${name}" with (force)`).catch(() => {});
    await adminPool.end();
  }
}

/** The DDL Better Auth would apply to the database behind `dsn`. */
export async function compileFor(dsn: string): Promise<{ sql: string; pending: number }> {
  const pool = scriptPool(dsn);
  try {
    const migrations = await getMigrations(consoleAuthSchemaOptions(pool) as never);
    const pending = migrations.toBeCreated.length + migrations.toBeAdded.length;
    const sql = pending === 0 ? "" : await migrations.compileMigrations();
    return { sql, pending };
  } finally {
    await pool.end();
  }
}

const HEADER = `-- GENERATED by \`bun run db:generate\` (console/db/generate.ts).
--
-- Produced by better-auth's own migration compiler
-- (\`better-auth/db/migration\` → \`getMigrations().compileMigrations()\`) at the
-- version pinned in package.json. \`--fresh\` diffs against an empty database and
-- emits the whole schema; without it, against a database that already has the
-- earlier migrations, and emits only what is new.
--
-- DO NOT EDIT. \`db/migrate.ts\` records a SHA-256 of this file when it is
-- applied and refuses to run once the content has changed. A better-auth
-- upgrade that alters the schema produces the NEXT numbered file; regenerating
-- this one in place would leave migrated and unmigrated environments disagreeing
-- with nothing to show for it.
--
-- Verified by \`tests/integration/console-db-migrations.test.ts\`: after every
-- committed migration is applied, better-auth must report nothing left to
-- create or add.
`;

async function main(): Promise<number> {
  const argv = process.argv.slice(2);
  const fresh = argv.includes("--fresh");
  const dsn = resolveDsn(argv, process.env);

  const { sql, pending } = fresh
    ? await withTemporaryDatabase(dsn, (temporary) => compileFor(temporary))
    : await compileFor(dsn);

  if (pending === 0) {
    console.error(`${redactDsn(dsn)}: better-auth reports no schema changes`);
    return 0;
  }

  process.stdout.write(`${HEADER}\n${sql.trimEnd()}\n`);
  console.error(`-- ${pending} table(s)/field group(s) emitted`);
  return 0;
}

if (import.meta.main) {
  try {
    process.exitCode = await main();
  } catch (error) {
    console.error(`console schema generation failed: ${(error as Error).message}`);
    process.exitCode = 1;
  }
}
